backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: src/images

collections:
  - name: store
    label: "Store Item" # Used in the UI, ie.: "New Post"
    folder: "src/images" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Name of Item", name: "title", widget: "string" }
      - {
          label: "Supported Meals",
          name: "categories",
          widget: "hidden",
          default: ["food"],
        }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Type of Food",
          name: "type",
          widget: "string",
          default: "raw bar",
        }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Main image", name: "image", widget: "image" }
